# Generated by Django 5.0.6 on 2024-05-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('prazo', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('A', 'Em andamento')], default='P', max_length=1)),
            ],
        ),
    ]
